// <auto-generated />
using System;
using Forest.Data.Models.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forest.Data.Migrations
{
    [DbContext(typeof(ForestContext))]
    [Migration("20250307204307_create_localdb_migration")]
    partial class create_localdb_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forest.Data.Models.Domain.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tracks")
                        .HasColumnType("int");

                    b.Property<int>("minutes")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.HasIndex("userId");

                    b.ToTable("Musics");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Orderline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MusicId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MusicId");

                    b.HasIndex("OrderId");

                    b.ToTable("Orderlines");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.User", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Artist", b =>
                {
                    b.HasOne("Forest.Data.Models.Domain.User", null)
                        .WithMany("Artists")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Genre", b =>
                {
                    b.HasOne("Forest.Data.Models.Domain.User", null)
                        .WithMany("Genres")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Music", b =>
                {
                    b.HasOne("Forest.Data.Models.Domain.Artist", null)
                        .WithMany("Musics")
                        .HasForeignKey("ArtistId");

                    b.HasOne("Forest.Data.Models.Domain.Genre", null)
                        .WithMany("Musics")
                        .HasForeignKey("GenreId");

                    b.HasOne("Forest.Data.Models.Domain.User", null)
                        .WithMany("Musics")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Order", b =>
                {
                    b.HasOne("Forest.Data.Models.Domain.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Orderline", b =>
                {
                    b.HasOne("Forest.Data.Models.Domain.Music", null)
                        .WithMany("Orderlines")
                        .HasForeignKey("MusicId");

                    b.HasOne("Forest.Data.Models.Domain.Order", null)
                        .WithMany("Orderlines")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Artist", b =>
                {
                    b.Navigation("Musics");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Genre", b =>
                {
                    b.Navigation("Musics");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Music", b =>
                {
                    b.Navigation("Orderlines");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.Order", b =>
                {
                    b.Navigation("Orderlines");
                });

            modelBuilder.Entity("Forest.Data.Models.Domain.User", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Genres");

                    b.Navigation("Musics");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
